# @package _global_
optim:
  epochs: 100
  optimizer:
    _target_: torch.optim.SGD
    lr: 0.1
    nesterov: False
  scheduler:
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.995
  freeze_layers_for_finetune:  # Default is False.