# @package _global_
optim:
  epochs: 100
  optimizer:
    _target_: torch.optim.Adam
    lr: 0.001
  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
    kwargs:
      T_0: 5
  freeze_layers_for_finetune: False # Default is False.