# @package _global_
optim:
  epochs: 20
  optimizer:
    _target_: torch.optim.Adam
    lr: 0.001
  scheduler:
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.995
  freeze_layers_for_finetune: True # Default is False.