# @package _global_
optim:
  epochs: 100
  optimizer:
    _target_: torch.optim.SGD
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0001
  scheduler:
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.95
  num_unfrozen: 0 # 0 = No freeze, 1 = freeze FC,   2 = freeze FC+block4,   ...