# @package _global_
_preprocessors:
  spectrogram:
    _target_: torchaudio.transforms.Spectrogram
    n_fft: ${data.n_fft}
    hop_length: ${data.hop_length}
  amplitude_2_db:
    _target_: torchaudio.transforms.AmplitudeToDB
  peak_norm:
    _target_: data.PeakNormalize
