# @package _global_
_augmentations:
  random_noise:
    _target_: soundbay.data_augmentation.AddGaussianNoise
    p: 0.5
    sr: ${data.sample_rate}
    snr: 15
  time_masking:
    _target_: soundbay.data_augmentation.TemporalMasking
    p: 0.5
    sr: ${data.sample_rate}
    max_secs: 0.2
  frequency_masking:
    _target_: soundbay.data_augmentation.FrequencyMasking
    p: 0.5
    sr: ${data.sample_rate}
    min_freq_in_segment: 2000
    max_freq_in_segment: ${data.max_freq}
    attenuation_gain: 120
    bandwidth_to_filter_out: 5000