# @package _global_
_augmentations:
  random_noise:
    _target_: audiomentations.AddGaussianSNR
    p: 0.5
    min_snr_in_db: 10
    max_snr_in_db: 20
  freq_shift:
    _target_: audiomentations.PitchShift
    min_semitones: -4
    max_semitones: 4
    p: 0.5
  time_masking:
    _target_: audiomentations.TimeMask
    min_band_part: 0.05
    max_band_part: 0.2
    p: 0.5
  frequency_masking:
    _target_: audiomentations.BandStopFilter
    min_center_freq: 500
    max_center_freq: ${data.max_freq}
    min_bandwidth_fraction: 0.05
    max_bandwidth_fraction: 0.2
    p: 0.5
