# @package _global_
_augmentations:
  # add_noise:
  #   _target_: soundbay.custom_audiomentations.AddMultichannelBackgroundNoise
  #   sounds_path:  '/mnt/c/Users/noam/whale/all_brazil_noise'
  #   min_snr_in_db: 3
  #   max_snr_in_db: 30
  #   lru_cache_size: 100
  #   p: 0.5

  time_stretch:
    _target_: audiomentations.TimeStretch
    min_rate: 0.9
    max_rate: 1.1
    p: 0.5
  time_masking:
    _target_: audiomentations.TimeMask
    min_band_part: 0.05
    max_band_part: 0.2
    p: 0.5
  frequency_masking:
    _target_: audiomentations.BandStopFilter

    min_center_freq: ${data.min_freq}
    min_bandwidth_fraction: 0.05
    max_bandwidth_fraction: 0.2
    p: 0.5
