# @package _global_
optim:
  epochs: 1000
  optimizer:
    _target_: torch.optim.SGD
    lr: 0.1
    weight_decay: 0.005
    nesterov: False
  scheduler:
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 1