data:
  label_names: 
    - Noise
    - Call
  batch_size: 64
  num_workers: 10
  sample_rate: 16000
  data_sample_rate: 44100
  min_freq: 0
  n_fft: 1024
  hop_length: 256
  label_type: single_label
  proba_threshold: 0.5
  audio_representation: spectrogram
  normalization: peak
  resize: false
  size: [224, 224]
  n_mels: 64
  seq_length: 1
  
  train_dataset:
    module_name: ClassifierDataset
    data_path: ./tests/assets/data/
    metadata_path: ./tests/assets/annotations/sample_annotations.csv
    mode: train
    path_hierarchy: 0
    augmentations_p: 0.8
    margin_ratio: 0.5
    slice_flag: false
    augmentations_config:
      pitch_shift_p: 0.0
      time_stretch_p: 0.5
      time_masking_p: 0.5
      frequency_masking_p: 0.5
      min_semitones: -4
      max_semitones: 4
      min_rate: 0.9
      max_rate: 1.1
      min_band_part: 0.05
      max_band_part: 0.2
      min_bandwidth_fraction: 0.05
      max_bandwidth_fraction: 0.2
      add_multichannel_background_noise_p: 0.0
      min_snr_in_db: 3
      max_snr_in_db: 30
      lru_cache_size: 100

  val_dataset:
    module_name: ClassifierDataset
    data_path: ./tests/assets/data
    metadata_path: ./tests/assets/annotations/sample_annotations.csv
    mode: val
    path_hierarchy: 0
    augmentations_p: 0.0
    margin_ratio: 0.0
    slice_flag: true
    augmentations_config:
      pitch_shift_p: 0.0

experiment:
  debug: true
  manual_seed: 1234
  project: finding_willy
  bucket_name: deepvoice-experiments
  artifacts_upload_limit: 64
  equalize_data: true
  checkpoint:
    resume: allow
    load_optimizer_state: false

model:
  module_name: ResNet1Channel
  num_classes: 2
  criterion: cross_entropy
  model_params:
    layers: [3, 4, 6, 3]
    block: torchvision.models.resnet.Bottleneck

optim:
  epochs: 100
  freeze_layers_for_finetune: true
  optimizer:
    module_name: torch.optim.Adam
    params:
      lr: 0.0005
  scheduler:
    module_name: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
    params:
      T_0: 5