# @package _global_
_preprocessors:
  mel_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: ${data.sample_rate}
    n_fft: ${data.n_fft}
    hop_length: ${data.hop_length}
    win_length: ${data.n_fft}
    pad_mode: 'constant'
    n_mels: 64
    f_min: ${data.min_freq}
#    f_max: ${data.sample_rate / 2}
  amplitude_2_db:
    _target_: torchaudio.transforms.AmplitudeToDB
    top_db: 180
    # ref: 
  # peak_norm:
  #   _target_: soundbay.data.PeakNormalize

