# @package _global_
_preprocessors:
  spectrogram:
    _target_: torchaudio.transforms.Spectrogram
    n_fft: ${data.n_fft}
    hop_length: ${data.hop_length}
  PCEN:
      _target_: soundbay.utils.signal_processing.LibrosaPcen
      sr: ${data.sample_rate}
      hop_length: ${data.hop_length}
      fmin: ${data.min_freq}
  min_freq_filtering:
    _target_: soundbay.data.MinFreqFiltering
    min_freq_filtering: ${data.min_freq}
    sample_rate: ${data.sample_rate}
  amplitude_2_db:
    _target_: torchaudio.transforms.AmplitudeToDB
  peak_norm:
    _target_: soundbay.data.PeakNormalize
