# @package _global_
_preprocessors:
  spectrogram:
    _target_: soundbay.data.MultiSpectrogram
    n_ffts: ${data.n_ffts}
    hop_lengths: ${data.hop_lengths}
  min_freq_filtering:
    _target_: soundbay.data.MinFreqFiltering
    min_freq_filtering: ${data.min_freq}
    sample_rate: ${data.sample_rate}
  amplitude_2_db:
    _target_: soundbay.data.MultiSpecAmplitudeToDB
  peak_norm:
    _target_: soundbay.data.PeakNormalize
  stack:
    _target_: soundbay.data.MultiSpecFusion
