AUDIO_DATA:
#  CLIP_SECS: 1.999
#  HOP_LENGTH: 5
  NUM_FRAMES: 342
  NUM_FREQUENCIES: 401
#  SAMPLING_RATE: 24000
#  WINDOW_LENGTH: 10
BN:
  FREEZE: True
  NORM_TYPE: batchnorm
  NUM_BATCHES_PRECISE: 200
  NUM_SPLITS: 1
  NUM_SYNC_DEVICES: 1
  USE_PRECISE_STATS: True
  WEIGHT_DECAY: 0.0
DATA:
#  ENSEMBLE_METHOD: sum
  INPUT_CHANNEL_NUM: [1, 1]
#  MULTI_LABEL: False
#DATA_LOADER:
#  ENABLE_MULTI_THREAD_DECODE: False
#  NUM_WORKERS: 1
#  PIN_MEMORY: True
#DIST_BACKEND: nccl
#EPICKITCHENS:
#  ANNOTATIONS_DIR: ../data
#  AUDIO_DATA_FILE: ../data/EPIC-KITCHENS-100_audio.hdf5
#  TEST_LIST: smaller_EPIC_100_train.pkl
#  TEST_SPLIT: validation
#  TRAIN_LIST: smaller_EPIC_100_train.pkl
#  TRAIN_PLUS_VAL: False
#  VAL_LIST: smaller_EPIC_100_train.pkl
#LOG_MODEL_INFO: True
#LOG_PERIOD: 10
MODEL:
  ARCH: slowfast
  DROPCONNECT_RATE: 0.0
  DROPOUT_RATE: 0.5
  FC_INIT_STD: 0.01
  HEAD_ACT: softmax
  LOSS_FUNC: cross_entropy
  MODEL_NAME: SlowFast
  MULTI_PATHWAY_ARCH: ['slowfast']
  NUM_CLASSES: [2, 2]
  SINGLE_PATHWAY_ARCH: ['slow', 'fast']
NUM_GPUS: 1
#NUM_SHARDS: 1
#OUTPUT_DIR: .
RESNET:
  DEPTH: 50
  FREQUENCY_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
  FREQUENCY_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  INPLACE_RELU: True
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  NUM_GROUPS: 1
  STRIDE_1X1: False
  TRANS_FUNC: bottleneck_transform
  WIDTH_PER_GROUP: 64
  ZERO_INIT_FINAL_BN: True
RNG_SEED: 0
SHARD_ID: 0
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
#SOLVER:
#  BASE_LR: 0.001
#  BASE_LR_SCALE_NUM_SHARDS: False
#  COSINE_END_LR: 0.0
#  DAMPENING: 0.0
#  GAMMA: 0.1
#  LRS: [1, 0.1, 0.01]
#  LR_POLICY: steps_with_relative_lrs
#  MAX_EPOCH: 30
#  MOMENTUM: 0.9
#  NESTEROV: True
#  OPTIMIZING_METHOD: sgd
#  STEPS: [0, 20, 25]
#  STEP_SIZE: 1
#  WARMUP_EPOCHS: -1.0
#  WARMUP_FACTOR: 0.1
#  WARMUP_START_LR: 0.01
#  WEIGHT_DECAY: 0.0001
#TENSORBOARD:
#  CATEGORIES_PATH:
#  CLASS_NAMES_PATH:
#  CONFUSION_MATRIX:
#    ENABLE: False
#    FIGSIZE: [8, 8]
#    SUBSET_PATH:
#  ENABLE: False
#  HISTOGRAM:
#    ENABLE: False
#    FIGSIZE: [8, 8]
#    SUBSET_PATH:
#    TOPK: 10
#  LOG_DIR:
#  PREDICTIONS_PATH:
#TEST:
#  BATCH_SIZE: 4
#  CHECKPOINT_FILE_PATH:
#  DATASET: epickitchens
#  ENABLE: False
#  NUM_ENSEMBLE_VIEWS: 10
#  SAVE_RESULTS_PATH:
#TRAIN:
#  AUTO_RESUME: True
#  BATCH_SIZE: 32
#  CHECKPOINT_CLEAR_NAME_PATTERN: ()
#  CHECKPOINT_EPOCH_RESET: True
#  CHECKPOINT_FILE_PATH:
#  CHECKPOINT_PERIOD: 1
#  DATASET: epickitchens
#  ENABLE: True
#  EVAL_PERIOD: 2
#VGGSOUND:
#  ANNOTATIONS_DIR: /home/shai/repos/auditory-slow-fast
#  AUDIO_DATA_DIR:
#  TEST_LIST: EPIC_100_train.pkl
#  TRAIN_LIST: EPIC_100_train.pkl
#  VAL_LIST: EPIC_100_train.pkl
#WANDB:
#  ENABLE: False
#  ENABLE: False
#  RUN_ID: