# @package _global_
model:
  criterion:
    _target_: torch.nn.CrossEntropyLoss
  model:
    _target_: models.ResNetNChannel
    layers: [3, 4, 6, 3]
    block: torchvision.models.resnet.BasicBlock
    num_classes: 2
